const express = require('express');
const router = express.Router();
const listaController = require('../controllers/listaController');
const tarefaController = require('../controllers/tarefaController');
router.get('/', listaController.listar);
router.post('/', listaController.criar);
router.put('/:id', listaController.atualizar);
router.delete('/:id', listaController.excluir);
router.post('/:listaId/tarefas', tarefaController.criar);
router.put('/:listaId/tarefas/:tarefaId', tarefaController.atualizar);
router.patch('/:listaId/tarefas/:tarefaId/status', tarefaController.alternarStatus);
router.delete('/:listaId/tarefas/:tarefaId', tarefaController.excluir);
module.exports = router;
